# Generated by Django 2.2 on 2020-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=10)),
                ('famsize', models.CharField(max_length=3)),
                ('Pstatus', models.CharField(max_length=10)),
                ('Medu', models.CharField(max_length=10)),
                ('Fedu', models.CharField(max_length=10)),
                ('Mjob', models.CharField(max_length=10)),
                ('Fjob', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=10)),
                ('guardian', models.CharField(max_length=10)),
                ('traveltime', models.CharField(max_length=1)),
                ('stime', models.CharField(max_length=1)),
                ('failures', models.CharField(max_length=1)),
                ('schoolsup', models.CharField(max_length=3)),
                ('famsup', models.CharField(max_length=3)),
                ('paid', models.CharField(max_length=10)),
                ('activities', models.CharField(max_length=10)),
                ('nursery', models.CharField(max_length=10)),
                ('higher', models.CharField(max_length=10)),
                ('internet', models.CharField(max_length=10)),
                ('famrel', models.CharField(max_length=10)),
                ('rom', models.CharField(max_length=10)),
                ('freetime', models.CharField(max_length=10)),
                ('goout', models.CharField(max_length=10)),
                ('dalc', models.CharField(max_length=10)),
                ('walc', models.CharField(max_length=10)),
                ('health', models.CharField(max_length=10)),
                ('absences', models.CharField(max_length=10)),
                ('g1', models.CharField(max_length=10)),
                ('g2', models.CharField(max_length=10)),
            ],
        ),
    ]
