# Generated by Django 2.2 on 2020-07-01 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20200701_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='Fedu',
            field=models.CharField(choices=[('0', 'None'), ('1', 'primary education'), ('2', '5th to 9th grade'), ('3', 'secondary education'), ('4', 'higher education')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='Fjob',
            field=models.CharField(choices=[('at_home', 'at_home'), ('health', 'health'), ('civil-services', 'civil-services'), ('teacher', 'teacher'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='Medu',
            field=models.CharField(choices=[('0', 'None'), ('1', 'primary education'), ('2', '5th to 9th grade'), ('3', 'secondary education'), ('4', 'higher education')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='Mjob',
            field=models.CharField(choices=[('at_home', 'at_home'), ('health', 'health'), ('civil-services', 'civil-services'), ('teacher', 'teacher'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='Pstatus',
            field=models.CharField(choices=[('T', 'Together'), ('A', 'Apart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='absences',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='activities',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='address',
            field=models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='dalc',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='famrel',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='famsize',
            field=models.CharField(choices=[('LE3', 'Less than 3'), ('GT3', 'Greater than 3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='mod',
            name='famsup',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='mod',
            name='freetime',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='g1',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='g2',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='goout',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='guardian',
            field=models.CharField(choices=[('mother', 'mother'), ('father', 'father'), ('legal-guardian', 'legal-guardian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='health',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='higher',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='internet',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='nursery',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='paid',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='reason',
            field=models.CharField(choices=[('home', 'home'), ('reputation', 'reputation'), ('course', 'course'), ('other', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='rom',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='schoolsup',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'Yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='mod',
            name='stime',
            field=models.CharField(choices=[('0', '<120min'), ('1', '120 to 180 min.'), ('2', '300 min. to 10 hours'), ('3', '>10 hours')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='traveltime',
            field=models.CharField(choices=[('0', '<15min'), ('1', '15 to 30 min.'), ('2', '30 min. to 1 hour'), ('3', '>1 hour')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mod',
            name='walc',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
