# Generated by Django 2.2 on 2020-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20200701_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField()),
                ('product_type', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.TextField()),
                ('nos', models.IntegerField()),
            ],
        ),
    ]
