# Generated by Django 2.2 on 2020-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='target',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
