# Generated by Django 2.2 on 2020-07-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_mod_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='Fedu',
            new_name='Fathereducation',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='Fjob',
            new_name='Fatherjob',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='Medu',
            new_name='Mothereducation',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='Mjob',
            new_name='Motherjob',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='Pstatus',
            new_name='Parentalstatus',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='dalc',
            new_name='dailyalcohol',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='famrel',
            new_name='familyrelations',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='famsize',
            new_name='familysize',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='famsup',
            new_name='familysupport',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='higher',
            new_name='highereducation',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='paid',
            new_name='paidsupport',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='reason',
            new_name='reasontojoinschool',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='rom',
            new_name='romanticrelationship',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='schoolsup',
            new_name='schoolsupport',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='stime',
            new_name='studytime',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='walc',
            new_name='weekendalcohol',
        ),
    ]
