# Generated by Django 2.2 on 2020-07-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_auto_20200701_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
