# Generated by Django 2.2 on 2020-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.TextField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('mother', models.TextField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
