# Generated by Django 2.2 on 2020-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='father',
            field=models.CharField(default='abcd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mother',
            field=models.CharField(max_length=50),
        ),
    ]
